// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
// For remote
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Platform;

import java.util.*;
public class DemoFirefox {
  private WebDriver driver;
  private Map<String, Object> vars;
  DesiredCapabilities capability = DesiredCapabilities.firefox();
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
	 // For local
	/* System.setProperty(
	    		"webdriver.chrome.driver", 
	    		"./src/chromedriver_linux64/chromedriver"
	);
    driver = new ChromeDriver();
    */
	 // For remote
	capability.setBrowserName("firefox");
	capability.setPlatform(Platform.LINUX);
	String nodeUrlChrome = "http://172.17.0.4:5555/wd/hub";
	driver = new RemoteWebDriver(
			new URL(nodeUrlChrome), capability);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() {
    driver.get("https://katalon-demo-cura.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1848, 1053));
    driver.findElement(By.id("btn-make-appointment")).click();
    driver.findElement(By.cssSelector(".form-horizontal > .form-group:nth-child(2)")).click();
    driver.findElement(By.id("txt-username")).sendKeys("John Doe");
    driver.findElement(By.id("txt-password")).sendKeys("ThisIsNotAPassword");
    driver.findElement(By.id("txt-password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("chk_hospotal_readmission")).click();
    driver.findElement(By.id("txt_visit_date")).click();
    driver.findElement(By.cssSelector(".datepicker-days > .table-condensed")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > .day:nth-child(3)")).click();
    driver.findElement(By.id("txt_comment")).click();
    driver.findElement(By.id("txt_comment")).sendKeys("BONJOUR LES COPAINS");
    driver.findElement(By.id("btn-book-appointment")).click();
    driver.findElement(By.linkText("Go to Homepage")).click();
    driver.findElement(By.id("menu-toggle")).click();
    driver.findElement(By.linkText("History")).click();
    driver.findElement(By.linkText("Go to Homepage")).click();
    driver.findElement(By.id("menu-toggle")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}