// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty(
	    		"webdriver.chrome.driver", 
	    		"./src/chromedriver_linux64/chromedriver"
	);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() {
    driver.get("https://katalon-demo-cura.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1848, 1053));
    driver.findElement(By.id("btn-make-appointment")).click();
    driver.findElement(By.cssSelector(".form-horizontal > .form-group:nth-child(2)")).click();
    driver.findElement(By.id("txt-username")).sendKeys("John Doe");
    driver.findElement(By.id("txt-password")).sendKeys("ThisIsNotAPassword");
    driver.findElement(By.id("txt-password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("chk_hospotal_readmission")).click();
    driver.findElement(By.id("txt_visit_date")).click();
    driver.findElement(By.cssSelector(".datepicker-days > .table-condensed")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > .day:nth-child(3)")).click();
    driver.findElement(By.id("txt_comment")).click();
    driver.findElement(By.id("txt_comment")).sendKeys("BONJOUR LES COPAINS");
    driver.findElement(By.id("btn-book-appointment")).click();
    driver.findElement(By.linkText("Go to Homepage")).click();
    driver.findElement(By.id("menu-toggle")).click();
    driver.findElement(By.linkText("History")).click();
    driver.findElement(By.linkText("Go to Homepage")).click();
    driver.findElement(By.id("menu-toggle")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}